version: "3.8"
services:
  app:
    container_name: express-modular-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      # setup file or folder
      - app-assets:/app/assets
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  app-assets:
    external: false
