version: '3.8'
services:
  express-modular-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - /mnt/storage/app-name-dev:/app/assets
    network_mode: bridge
    extra_hosts:
      - 'host.docker.internal:host-gateway'
