name: 🚀 Deploy App...
on:
  push:
    branches: ['master']
jobs:
  app-deploy:
    name: 🚚 BackEnd (Test Build Docker) - Express Modular API
    runs-on: ubuntu-latest
    steps:
      - name: 🎉 Get latest code
        uses: actions/checkout@v2

      - name: Rename ENV...
        run: |
          mv .env.example .env

      # ----------------------------------------------------------------------
      # ----------------------------------------------------------------------
      # ----------------------------------------------------------------------

      - name: 📡 Docker Test...
        run: |
          docker build -t my-docker-image .

      - name: ✅ Ready to Use!
        run: echo "success build docker!"
      # ----------------------------------------------------------------------
      # ----------------------------------------------------------------------
      # ----------------------------------------------------------------------
